#!/usr/bin/perl

use strict;

my $user = $ENV{'USER'};
my $base_path = $ENV{'PWD'};
my $out = "$base_path/out";
#gaoyuxia@wind-mobi.com 20180929
my $all_symbols = "$out/all_symbols";
#gaoyuxia@wind-mobi.com 20180929

if(-d $out)
{
    system("rm -rf $out");
}
#gaoyuxia@wind-mobi.com 20180929
system("mkdir -p $out/all_symbols");
#gaoyuxia@wind-mobi.com 20180929

chdir("$base_path/MSM8937.LA.3.0.1/common/build");
system("python build.py");
chdir($base_path);
print("Split finished!!!\n");

#NON-HLOS.bin
system("cp $base_path/MSM8937.LA.3.0.1/common/build/bin/asic/NON-HLOS.bin $out");
#rpm.mbn
system("cp $base_path/RPM.BF.2.2/rpm_proc/build/ms/bin/8937/rpm.mbn $out");
#prog_emmc_firehose_8917_lite.mbn
system("cp $base_path/BOOT.BF.3.3/boot_images/build/ms/bin/FAADANAZ/prog_emmc_firehose_8937_ddr.mbn $out");
#prog_emmc_firehose_8917_ddr.mbn
system("cp $base_path/BOOT.BF.3.3/boot_images/build/ms/bin/FAADANAZ/prog_emmc_firehose_8937_lite.mbn $out");
#sbl1.mbn
system("cp $base_path/BOOT.BF.3.3/boot_images/build/ms/bin/FAASANAZ/sbl1.mbn $out");
#dongqinling@wind-mobi.com start
system("cp $base_path/MPSS.JO.3.0/modem_proc/build/ms/orig_MODEM_PROC_IMG_8937.genns.prodQ.elf $out");
#dongqinling@wind-mobi.com end
#huangshaopeng@wind-mobi.com 20170911 begin
#adspso.bin  
system("cp $base_path/ADSP.8953.2.8.4/adsp_proc/build/dynamic_signed/8937/adspso.bin $out");

#cmnlib.mbn  cmnlib64.mbn  devcfg.mbn  keymaster.mbn  lksecapp.mbn
my @tz_list = ("cmnlib.mbn", "cmnlib_30.mbn", "keymaster64.mbn", "cmnlib64.mbn", "cmnlib64_30.mbn", "devcfg.mbn", "keymaster.mbn");
foreach (@tz_list)
{
    system("cp $base_path/TZ.BF.4.0.5/trustzone_images/build/ms/bin/ZALAANAA/$_ $out");
}
#huangshaopeng@wind-mobi.com 20170911 end

#tz.mbn
system("cp $base_path/TZ.BF.4.0.5/trustzone_images/build/ms/bin/ZALAANAA/tz.mbn $out");
#gpt_backup0.bin gpt_both0.bin gpt_main0.bin patch0.xml
my @gpt_list = ("gpt_backup0.bin", "gpt_both0.bin", "gpt_main0.bin", "patch0.xml");
foreach (@gpt_list)
{
    system("cp $base_path/MSM8937.LA.3.0.1/common/build/$_ $out");
}
#emmc_appsboot.mbn boot.img recovery.img mdtp.img
my @ap_list = ("emmc_appsboot.mbn", "boot.img", "mdtp.img", "vmlinux","fs_image.tar.gz.mbn.img","splash.img", "recovery.img");
foreach (@ap_list)
{
    system("cp $base_path/LA.UM.6.6/LINUX/android/out/target/product/msm8937_64/$_ $out");
}
#split img
system("cp $base_path/MSM8937.LA.3.0.1/common/build/bin/asic/sparse_images/* $out");

#gaoyuxia@wind-mobi.com 20180929u
system("cp ./../out/target/product/msm8937_64/obj/KERNEL_OBJ/vmlinux $all_symbols");
system("cp -rf --parents ./CNSS.PR.4.0/wcnss_proc/build/ms/*.elf $all_symbols");
system("cp -rf --parents ./RPM.BF.2.2/rpm_proc/core/bsp/rpm/build/RPM_AAAAANAAR.elf $all_symbols");
system("cp -rf --parents ./MPSS.JO.3.0/modem_proc/build/ms/*.elf $all_symbols");
system("cp -rf --parents ./MPSS.JO.3.0/modem_proc/build/myps/qshrink/msg_hash.txt $all_symbols");
system("cp -rf --parents ./TZ.BF.4.0.5/trustzone_images/core/bsp/qsee/build/ZALAANAA/qsee.elf $all_symbols");
system("cp -rf --parents ./ADSP.8953.2.8.4/adsp_proc/build/ms/*.elf $all_symbols");
system("cp -rf --parents ./ADSP.8953.2.8.4/adsp_proc/qdsp6/qshrink/src/msg_hash.txt $all_symbols");
system("cp -rf --parents ./TZ.BF.4.0.5/trustzone_images/core/bsp/qsee/build/ZALAANAA/qsee.elf $all_symbols");
system("cp -rf --parents ./ADSP.8953.2.8.4/adsp_proc/build/ms/*.elf $all_symbols");
system("cp -rf --parents ./ADSP.8953.2.8.4/adsp_proc/qdsp6/qshrink/src/msg_hash.txt $all_symbols");
#gaoyuxia@wind-mobi.com 20180929

=pod
=cut
my ($sec, $min, $hour, $day, $month, $year, $a, $b, $c) = localtime(time);
my $zip_name = sprintf("FlashPackage_S200X-U100C_QFIL.zip", $year+1990, $month+1, $day, $hour, $min, $sec);
print "$zip_name\n";

chdir("$base_path/out");
#dongqinling@wind-mobi.com start 20180523
system("cp rawprogram_unsparse.xml rawprogram_unsparse_upgrade.xml");
system("sed -i 's/factory_1.img//' rawprogram_unsparse_upgrade.xml");
system("sed -i 's/esim_1.img//' rawprogram_unsparse_upgrade.xml");
#dongqinling@wind-mobi.com end 20180523

#gaoyuxia@wind-mobi.com 20180929
system("zip -r -9 $zip_name ./*");
system("cp FlashPackage_S200X-U100C_QFIL.zip /data/mine/test/MT6572/$user");
#gaoyuxia@wind-mobi.com 20180929

