set PROJECT1=%1
set PROJECT2=%2
set SOURCE_URL=%3
set TARGET_URL=%4
SOURCE_UR=G:\swbackup2\Project_Release\Qualcomm\8976\T10_LA1.1.1_Branch
TARGET_URL=F:\sw_public\Project_Release\Qualcomm\8976\T10_LA1.1.1_Branch

CD %SOURCE_UR%
MKDIR %PROJECT1%
CD %PROJECT1%
MKDIR Release
CD Release
COPY %TARGET_URL%\%PROJECT1%\Release\%PROJECT1%_Release_Notes.doc .
COPY %TARGET_URL%\%PROJECT1%\Release\Platform_upgrade_Release.txt .
CD ../
MKDIR target
CD target
MKDIR LTE_PRC
CD LTE_PRC
MKDIR ENG
CD ENG
COPY %TARGET_URL%\%PROJECT1%\target\LTE_PRC\ENG\%PROJECT2%.zip .
COPY %TARGET_URL%\%PROJECT1%\target\LTE_PRC\ENG\%PROJECT2%_OriginalFactory.zip .
COPY %TARGET_URL%\%PROJECT1%\target\LTE_PRC\ENG\DEBUG_INFO.zip .
MKDIR sd
CD sd
COPY %TARGET_URL%\%PROJECT1%\target\LTE_PRC\ENG\sd\%PROJECT2%_otafull.zip .
COPY %TARGET_URL%\%PROJECT1%\target\LTE_PRC\ENG\sd\%PROJECT2%-target_files.zip .
CD ../../
MKDIR USER
CD USER
COPY %TARGET_URL%\%PROJECT1%\target\LTE_PRC\ENG\%PROJECT1%.zip .
COPY %TARGET_URL%\%PROJECT1%\target\LTE_PRC\ENG\%PROJECT1%_OriginalFactory.zip .
COPY %TARGET_URL%\%PROJECT1%\target\LTE_PRC\ENG\DEBUG_INFO.zip .
MKDIR sd
CD sd
COPY %TARGET_URL%\%PROJECT1%\target\LTE_PRC\ENG\sd\%PROJECT1%_otafull.zip .
COPY %TARGET_URL%\%PROJECT1%\target\LTE_PRC\ENG\sd\%PROJECT1%-target_files.zip .
COPY %TARGET_URL%\%PROJECT1%\target\LTE_PRC\ENG\sd\%PROJECT1%.zip .
CD ../../
MKDIR FACTORY
CD FACTORY
COPY %TARGET_URL%\%PROJECT1%\target\LTE_PRC\FACTORY\%PROJECT1%_FACTORY.zip .
COPY %TARGET_URL%\%PROJECT1%\target\LTE_PRC\FACTORY\%PROJECT2%_FACTORY.zip .
COPY %TARGET_URL%\%PROJECT1%\target\LTE_PRC\FACTORY\%PROJECT1%_FACTORY.MD5.txt.zip .
COPY %TARGET_URL%\%PROJECT1%\target\LTE_PRC\FACTORY\%PROJECT2%_FACTORY.MD5.txt.zip .